/* tslint:disable */
/* eslint-disable */
/**
 * nuthatch
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { UserProfile, UserProfileFromJSON, UserProfileFromJSONTyped, UserProfileToJSON } from './UserProfile';

/**
 *
 * @export
 * @interface CurrentUser
 */
export interface CurrentUser {
  /**
   *
   * @type {string}
   * @memberof CurrentUser
   */
  email?: string;
  /**
   *
   * @type {boolean}
   * @memberof CurrentUser
   */
  isActivated: boolean;
  /**
   *
   * @type {UserProfile}
   * @memberof CurrentUser
   */
  profile: UserProfile;
}

export function CurrentUserFromJSON(json: any): CurrentUser {
  return CurrentUserFromJSONTyped(json, false);
}

export function CurrentUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentUser {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: !exists(json, 'email') ? undefined : json['email'],
    isActivated: json['isActivated'],
    profile: UserProfileFromJSON(json['profile']),
  };
}

export function CurrentUserToJSON(value?: CurrentUser | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
    isActivated: value.isActivated,
    profile: UserProfileToJSON(value.profile),
  };
}
