/* tslint:disable */
/* eslint-disable */
/**
 * nuthatch
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface EmailLoginCred
 */
export interface EmailLoginCred {
  /**
   *
   * @type {string}
   * @memberof EmailLoginCred
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof EmailLoginCred
   */
  initialPassword: string;
}

export function EmailLoginCredFromJSON(json: any): EmailLoginCred {
  return EmailLoginCredFromJSONTyped(json, false);
}

export function EmailLoginCredFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailLoginCred {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: json['email'],
    initialPassword: json['initialPassword'],
  };
}

export function EmailLoginCredToJSON(value?: EmailLoginCred | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
    initialPassword: value.initialPassword,
  };
}
