/* tslint:disable */
/* eslint-disable */
/**
 * nuthatch
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface OAuth1TempCred
 */
export interface OAuth1TempCred {
  /**
   *
   * @type {string}
   * @memberof OAuth1TempCred
   */
  provider: string;
  /**
   *
   * @type {string}
   * @memberof OAuth1TempCred
   */
  oauthToken: string;
  /**
   *
   * @type {string}
   * @memberof OAuth1TempCred
   */
  oauthVerifier: string;
}

export function OAuth1TempCredFromJSON(json: any): OAuth1TempCred {
  return OAuth1TempCredFromJSONTyped(json, false);
}

export function OAuth1TempCredFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuth1TempCred {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    provider: json['provider'],
    oauthToken: json['oauthToken'],
    oauthVerifier: json['oauthVerifier'],
  };
}

export function OAuth1TempCredToJSON(value?: OAuth1TempCred | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    provider: value.provider,
    oauthToken: value.oauthToken,
    oauthVerifier: value.oauthVerifier,
  };
}
