# have to use node16 before prisma fixes https://github.com/prisma/prisma/issues/10649 
FROM node:16-bullseye-slim

COPY . /opt/voxscape

RUN set -uex && \
        cd /opt/voxscape/web && yarn --version && yarn && yarn prisma generate && yarn build
