################ stage 0

FROM node:18-bullseye-slim

# uid=1000 gid=1000
USER node

COPY --chown=node:node . /opt/voxscape

RUN \
    --mount=type=cache,target=/home/node/.yarn,sharing=locked,uid=1000,gid=1000 \
    --mount=type=cache,target=/home/node/.cache,sharing=locked,uid=1000,gid=1000 \
    --mount=type=cache,target=/opt/voxscape/.yarn/cache,sharing=locked,uid=1000,gid=1000 \
    set -uex && \
    cd /opt/voxscape/web && \
    yarn --version && \
    yarn config get cacheFolder && \
    yarn && yarn prisma generate && \
    mkdir -pv .next # required to make .next writable WTF

RUN \
    --mount=type=cache,target=/opt/voxscape/web/.next/cache,sharing=locked,uid=1000,gid=1000 \
    set -uex && \
    find /opt/voxscape/web/.next/cache && \
    cd /opt/voxscape/web && yarn build && \
    cd /opt/voxscape && yarn workspaces focus --production

################ stage 1

FROM node:18-bullseye-slim

RUN npm i -g publicaddr && which publicaddr

USER node

COPY --from=0 --chown=node:node . /opt/voxscape
