# vim: ft=Dockerfile
################ stage 0

FROM node:18-bookworm-slim

# bookworm doesn't have openssl installed now.
RUN apt-get update && apt-get install openssl

# uid=1000 gid=1000
USER node

COPY --chown=node:node . /opt/voxscape

RUN \
    --mount=type=cache,target=/home/node/.yarn,sharing=locked,uid=1000,gid=1000 \
    --mount=type=cache,target=/home/node/.cache,sharing=locked,uid=1000,gid=1000 \
    --mount=type=cache,target=/opt/voxscape/.yarn/cache,sharing=locked,uid=1000,gid=1000 \
    set -uex && \
    cd /opt/voxscape/web && \
    yarn --version && \
    yarn config get cacheFolder && \
    yarn && yarn prisma generate && \
    mkdir -pv .next # required to make .next writable WTF

RUN \
    --mount=type=cache,target=/opt/voxscape/web/.next/cache,sharing=locked,uid=1000,gid=1000 \
    set -uex && \
    find /opt/voxscape/web/.next/cache && \
    cd /opt/voxscape/web && yarn build

RUN \
    --mount=type=cache,target=/home/node/.yarn,sharing=locked,uid=1000,gid=1000 \
    --mount=type=cache,target=/home/node/.cache,sharing=locked,uid=1000,gid=1000 \
    --mount=type=cache,target=/opt/voxscape/.yarn/cache,sharing=locked,uid=1000,gid=1000 \
    cd /opt/voxscape/web && yarn workspaces focus @voxscape/web --production && yarn prisma generate

################ stage 1

FROM node:18-bookworm-slim

# bookworm doesn't have openssl installed now.
RUN apt-get update && apt-get install openssl && apt-get clean

RUN npm i -g publicaddr@0.4.3 && which publicaddr

USER node

COPY --from=0 --chown=node:node /opt/voxscape /opt/voxscape
