name: Check code

on:
  workflow_call: {}

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  check-vox-ts:
    name: Check vox.ts
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: 'yarn.lock'
      - run: yarn
      - run: yarn lint
        working-directory: ./packages/vox.ts/
      - run: yarn typecheck
        working-directory: ./packages/vox.ts/
      - run: yarn test
        working-directory: ./packages/vox.ts/

  check-web:
    name: Check web
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./web/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: 'yarn.lock'
      - uses: actions/cache@v3
        with:
          path: ./web/.next
          key: next-build-cache-${{ hashFiles('yarn.lock') }}
      - run: docker compose -f ../dev/docker-compose.yml up -d
      - run: yarn
      - run: yarn prisma generate
      - run: yarn typecheck
      - run: yarn lint
      - run: yarn test:init-db
      - run: yarn test
      - run: docker compose -f ../dev/docker-compose.yml down
      - run: yarn build
